// 
// Generated by @himenon/openapi-typescript-code-generator v0.13.2
// 
// OpenApi : 3.0.1
// 
// 


export namespace Schemas {
    export interface WeatherForecast {
        date?: string;
        temperatureC?: number;
        temperatureF?: number;
        summary?: string | null;
    }
}
